const categories = [
    "Natural Language Processing",
    "Speech Recognition",
    "Computer Vision",
    "Image Recognition",
    "Object Detection",
    "Facial Recognition",
    "Gesture Recognition",
    "Machine Learning Algorithms",
    "Deep Learning",
    "Reinforcement Learning",
    "Predictive Analytics",
    "Recommendation Systems",
    "Chatbots",
    "Virtual Assistants",
    "Autonomous Vehicles",
    "Robotics",
    "Healthcare AI",
    "Finance and Banking AI",
    "Cybersecurity",
    "Supply Chain Optimization",
    "Education Technology (EdTech)",
    "Agricultural AI",
    "Energy Management",
    "Human Resources",
    "Emotion Recognition",
    "Financial Trading",
    "Natural Resource Exploration",
    "Game AI",
    "Augmented Reality (AR)"
  ]
